#
# Docker Compose
#

compose-up: ## Start docker-compose services, e.g for integration tests against AWS services
	docker-compose up -d

compose-down: ## Stop and remove containers
	docker-compose down

compose-restart: ## Restart
	docker-compose restart
